// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data_sync.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	data_sync.proto

It has these top-level messages:
	SegmentCacheRequest
	AppCacheRequest
	CampaignCacheRequest
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SegmentCacheRequest struct {
	Sadd      []string `protobuf:"bytes,1,rep,name=sadd" json:"sadd,omitempty"`
	Srem      []string `protobuf:"bytes,2,rep,name=srem" json:"srem,omitempty"`
	SegmentId int64    `protobuf:"varint,3,opt,name=segment_id,json=segmentId" json:"segment_id,omitempty"`
}

func (m *SegmentCacheRequest) Reset()                    { *m = SegmentCacheRequest{} }
func (m *SegmentCacheRequest) String() string            { return proto1.CompactTextString(m) }
func (*SegmentCacheRequest) ProtoMessage()               {}
func (*SegmentCacheRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SegmentCacheRequest) GetSadd() []string {
	if m != nil {
		return m.Sadd
	}
	return nil
}

func (m *SegmentCacheRequest) GetSrem() []string {
	if m != nil {
		return m.Srem
	}
	return nil
}

func (m *SegmentCacheRequest) GetSegmentId() int64 {
	if m != nil {
		return m.SegmentId
	}
	return 0
}

type AppCacheRequest struct {
	AppId   string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	EventId string `protobuf:"bytes,2,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
}

func (m *AppCacheRequest) Reset()                    { *m = AppCacheRequest{} }
func (m *AppCacheRequest) String() string            { return proto1.CompactTextString(m) }
func (*AppCacheRequest) ProtoMessage()               {}
func (*AppCacheRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppCacheRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AppCacheRequest) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

type CampaignCacheRequest struct {
	CampaignId string `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId" json:"campaign_id,omitempty"`
	EventId    string `protobuf:"bytes,2,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
}

func (m *CampaignCacheRequest) Reset()                    { *m = CampaignCacheRequest{} }
func (m *CampaignCacheRequest) String() string            { return proto1.CompactTextString(m) }
func (*CampaignCacheRequest) ProtoMessage()               {}
func (*CampaignCacheRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CampaignCacheRequest) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *CampaignCacheRequest) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*SegmentCacheRequest)(nil), "proto.SegmentCacheRequest")
	proto1.RegisterType((*AppCacheRequest)(nil), "proto.AppCacheRequest")
	proto1.RegisterType((*CampaignCacheRequest)(nil), "proto.CampaignCacheRequest")
	proto1.RegisterType((*Response)(nil), "proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DataSync service

type DataSyncClient interface {
	SegmentCache(ctx context.Context, in *SegmentCacheRequest, opts ...grpc.CallOption) (*Response, error)
	CampaignCache(ctx context.Context, in *CampaignCacheRequest, opts ...grpc.CallOption) (*Response, error)
	AppCache(ctx context.Context, in *AppCacheRequest, opts ...grpc.CallOption) (*Response, error)
}

type dataSyncClient struct {
	cc *grpc.ClientConn
}

func NewDataSyncClient(cc *grpc.ClientConn) DataSyncClient {
	return &dataSyncClient{cc}
}

func (c *dataSyncClient) SegmentCache(ctx context.Context, in *SegmentCacheRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.DataSync/SegmentCache", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncClient) CampaignCache(ctx context.Context, in *CampaignCacheRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.DataSync/CampaignCache", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncClient) AppCache(ctx context.Context, in *AppCacheRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.DataSync/AppCache", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DataSync service

type DataSyncServer interface {
	SegmentCache(context.Context, *SegmentCacheRequest) (*Response, error)
	CampaignCache(context.Context, *CampaignCacheRequest) (*Response, error)
	AppCache(context.Context, *AppCacheRequest) (*Response, error)
}

func RegisterDataSyncServer(s *grpc.Server, srv DataSyncServer) {
	s.RegisterService(&_DataSync_serviceDesc, srv)
}

func _DataSync_SegmentCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncServer).SegmentCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataSync/SegmentCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncServer).SegmentCache(ctx, req.(*SegmentCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSync_CampaignCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncServer).CampaignCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataSync/CampaignCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncServer).CampaignCache(ctx, req.(*CampaignCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSync_AppCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncServer).AppCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataSync/AppCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncServer).AppCache(ctx, req.(*AppCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataSync",
	HandlerType: (*DataSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SegmentCache",
			Handler:    _DataSync_SegmentCache_Handler,
		},
		{
			MethodName: "CampaignCache",
			Handler:    _DataSync_CampaignCache_Handler,
		},
		{
			MethodName: "AppCache",
			Handler:    _DataSync_AppCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_sync.proto",
}

func init() { proto1.RegisterFile("data_sync.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0x87, 0x5f, 0xca, 0xdb, 0x0a, 0xa3, 0x06, 0x33, 0xfe, 0x09, 0x56, 0x8d, 0x84, 0x13, 0xa7,
	0x1e, 0x34, 0x1e, 0x8d, 0x31, 0x78, 0xe1, 0xba, 0xbd, 0x9a, 0x34, 0x23, 0x3b, 0xc1, 0x1e, 0x80,
	0x95, 0x5d, 0x4d, 0xfa, 0xf1, 0xfc, 0x66, 0xa6, 0xdb, 0x25, 0x8a, 0x21, 0x9e, 0x76, 0xf6, 0x99,
	0x99, 0x27, 0xbb, 0x3f, 0x88, 0x24, 0x19, 0x5a, 0xe9, 0x4d, 0x53, 0x2e, 0x54, 0xd7, 0x9a, 0x16,
	0xa7, 0xf6, 0x48, 0x9f, 0xe1, 0x78, 0xc9, 0x55, 0xcd, 0x8d, 0xc9, 0xa9, 0x7c, 0x65, 0xc1, 0x6f,
	0xef, 0xac, 0x0d, 0x22, 0xfc, 0xd7, 0x24, 0x65, 0xec, 0x25, 0x7e, 0x16, 0x0a, 0x5b, 0x5b, 0xd6,
	0x71, 0x1d, 0x4f, 0x1c, 0xeb, 0xb8, 0xc6, 0x2b, 0x00, 0xbd, 0x5b, 0x5f, 0xad, 0x65, 0xec, 0x27,
	0x5e, 0xe6, 0x8b, 0xd0, 0x91, 0x42, 0xa6, 0x39, 0x44, 0x8f, 0x4a, 0x0d, 0xcc, 0xa7, 0x30, 0x23,
	0xa5, 0xb6, 0xd3, 0x5e, 0xe2, 0x65, 0xa1, 0x98, 0x92, 0x52, 0x85, 0xc4, 0x73, 0x08, 0xf8, 0xc3,
	0x69, 0x26, 0xb6, 0xb1, 0x67, 0xef, 0x85, 0x4c, 0x05, 0x9c, 0xe4, 0x54, 0x2b, 0x5a, 0x57, 0xcd,
	0xc0, 0x74, 0x0d, 0xfb, 0xa5, 0xe3, 0xdf, 0x3a, 0xe8, 0xd1, 0xdf, 0xce, 0x4b, 0x08, 0x04, 0x6b,
	0xd5, 0x36, 0x9a, 0xf1, 0x08, 0xfc, 0x5a, 0x57, 0x6e, 0x7f, 0x5b, 0xde, 0x7c, 0x7a, 0x10, 0x3c,
	0x91, 0xa1, 0xe5, 0xa6, 0x29, 0xf1, 0x1e, 0x0e, 0x7e, 0x26, 0x84, 0xf3, 0x5d, 0x80, 0x8b, 0x91,
	0xd8, 0xe6, 0x91, 0xeb, 0xf5, 0xee, 0xf4, 0x1f, 0x3e, 0xc0, 0xe1, 0xe0, 0xf5, 0x78, 0xe1, 0x66,
	0xc6, 0xfe, 0x34, 0x26, 0xb8, 0x83, 0xa0, 0xcf, 0x10, 0xcf, 0x5c, 0xfb, 0x57, 0xa8, 0x23, 0x6b,
	0x2f, 0x33, 0x4b, 0x6e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x84, 0x08, 0xd3, 0xf9, 0x01,
	0x00, 0x00,
}
