swagger: '2.0'
info:
  version: 1.0.0
  title: Greeting Server
paths:
  /hello:
    get:
      produces:
        - text/plain
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: defaults to World if not given
      operationId: getGreeting
      responses:
        200:
          description: returns a greeting
          schema:
              type: string
              description: contains the actual greeting as plain text

definitions:
  person:
    type: object
    properties:
      id:
        type: integer
        format: int
        readOnly: true
      first_name:
        type: string
        minLength: 1
      IfMarried:
        type: boolean